server:
  port: 8001

mybatis:
  type-aliases-package: com.komorebi.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&charcterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:    # 修改默认名字
    instance-id: springcloud-provider-dept8001
    prefer-ip-address: true     # 为 true 可以显示客户端 ip
# 配置Eureka链接的info信息
info:
  app.name: komorebi
  company: komorebi.blog